### ISSUE TITLE
Inconsistent constant notation & unnamed constants

### ISSUE THREAD

**Issue by Lewiscowles1986** [TOMB5/TOMB5#170]
Firstly, well done, this is super-readable C

A Few places in the code I've seen magic constants 256, 512, 0x80 (128)

I'm pretty sure these are all flags.

It's one thing to have them as magic constants. I suppose only through testing can they get names, but would you be open to receiving a PR to stabilize the notation?

**Comment by zdimension** [comment]
Is the first line sarcastic?
If yes then sorry, the code we're decompiling is from Core Design™ so it's a necessary evil.

These are indeed probably flags that we haven't yet had the time to replace by constants so we would totally be open to a PR about that, we are open to all PRs currently.

Because of the way the original engines were written, such constants are omnipresent and it's often hard to find which one was used in *this* or *that* precise context, but feel free to submit PRs, you would have all our gratitude ^^

By the way most of us (developers) are on the TR modding Discord server, whose link is available somewhere on README.md.

**Comment by Gh0stBlade** [comment]
@Lewiscowles1986 

Hi and welcome :)

I am currently aware that there are some raw constants that need to be converted to either enumeration or macro. Some of this is slowly being corrected but sometimes its not possible unless the underlying game logic for the said flag or const is decompiled. If you want to update something we are always open to PRs.

Feel free to improve the code where you can.

Cheers.

**Comment by Lewiscowles1986** [comment]
@zdimension 

> Is the first line sarcastic?
> If yes then sorry, the code we're decompiling is from Core Design™ so it's a necessary evil. The dim bulbs who wrote the engine didn't really think everything out when they first designed it so spaghetti code and weird hacks are to be expected :/

It wasn't, but colour me embarrassed :blush: I've seen much worse game code, especially RE

@Gh0stBlade thank you for the welcome too

It'll be the weekend before I look again, but it's looking to be a long one (I feared what @zdimension said about these being magic) so chances are good I'll PR the changes I think are worth it. It'll probably be iterative. Tackling notation first

**Comment by zdimension** [comment]
Oh okay, that makes sense. If you need any help in making your PR feel free to ask me or @Gh0stBlade, even we sometimes have trouble re-reading our own code because of how everything's structured.

The current goal of the project is to stay as close as we can, structurally speaking, to the original codebase. We'll start refactoring once we have a working version.

Also, currently types (structs, enums, etc) aren't really organized in any way, so it may be quite hard to find what enum goes where. That being said I highly doubt you'll have to create any since almost all enums of the original game are present in our headers so if you have trouble finding one ask me ^^
